version: "2.2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vision'
      MYSQL_USER: 'vision_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql
  backend:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=vision_user
      - DB_PASSWORD=password
      - DB_NAME=vision
    ports:
      - '9000:9000'
    volumes:
      - .:/app/