# https://taskfile.dev

version: '3'

tasks:
  format:
    cmds:
      - black .
  check_formatting:
    cmds:
      - black --check .
  run_dev:
    cmds:
      - FLASK_ENV=development flask run
  setup_db:
    cmds:
      - alembic upgrade head
