# https://taskfile.dev

version: '3'

tasks:
  format:
    cmds:
      - black .
  linter:
    cmds:
      - flake8 .
  run_dev:
    cmds:
      - FLASK_ENV=development DB_HOST=localhost DB_PORT=3306 DB_USER=vision_user DB_PASSWORD=password DB_NAME=vision flask run
  setup_db:
    cmds:
      - alembic upgrade head
