# https://taskfile.dev

version: '3'

tasks:
  format:
    cmds:
      - black .
  check_formatting:
    cmds:
      - black --check .
  run_dev:
    cmds:
      - DB_HOST=localhost DB_PORT=3306 DB_USER=vision_user DB_PASSWORD=password DB_NAME=vision FLASK_ENV=development flask run
