"""init

Revision ID: 9e3f23e8ab42
Revises: 
Create Date: 2020-10-17 22:29:08.152419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e3f23e8ab42"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=True),
        sa.Column("url", sa.String(length=100), nullable=True),
        sa.Column("suffix", sa.String(length=40), nullable=True),
        sa.Column("ip_address", sa.String(length=20), nullable=True),
        sa.Column("udp_supported", sa.Boolean(), nullable=True),
        sa.Column("ptz_app", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "camera_sub_streams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera", sa.Integer(), nullable=True),
        sa.Column("sub_stream", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["camera"], ["cameras.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cameras_configurations",
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configurations.id"],
        ),
        sa.PrimaryKeyConstraint("camera_id", "configuration_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cameras_configurations")
    op.drop_table("camera_sub_streams")
    op.drop_table("configurations")
    op.drop_table("cameras")
    # ### end Alembic commands ###
