"""add subnet

Revision ID: bb7707233dcb
Revises: d136209d4624
Create Date: 2020-11-12 13:46:49.398778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "bb7707233dcb"
down_revision = "d136209d4624"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configurations", sa.Column("subnet", mysql.VARCHAR(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configurations", "subnet")
    # ### end Alembic commands ###
