"""settings

Revision ID: b4d524477ee6
Revises: bb7707233dcb
Create Date: 2020-12-02 06:51:42.009166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b4d524477ee6"
down_revision = "bb7707233dcb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", mysql.INTEGER(), nullable=False),
        sa.Column("path", mysql.VARCHAR(length=256), nullable=True),
        sa.Column("udp_preferred", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
