"""add rows

Revision ID: c8cdd351e4a1
Revises: b4d524477ee6
Create Date: 2021-04-13 16:34:34.630928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c8cdd351e4a1"
down_revision = "b4d524477ee6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cameras", sa.Column("login", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column(
        "cameras", sa.Column("password", mysql.VARCHAR(length=128), nullable=True)
    )
    op.add_column("cameras", sa.Column("port", mysql.INTEGER(), nullable=True))
    op.add_column("cameras", sa.Column("ptz_port", mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "ptz_port")
    op.drop_column("cameras", "port")
    op.drop_column("cameras", "password")
    op.drop_column("cameras", "login")
    # ### end Alembic commands ###
